services:
  server:
    restart: on-failure
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=12345678
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

volumes:
  redisdata: