// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDishOrderList = "dish_order_list"

// DishOrderList mapped from table <dish_order_list>
type DishOrderList struct {
	DishOrderID int64     `gorm:"column:dish_order_id;primaryKey" json:"dish_order_id"`
	DishID      int64     `gorm:"column:dish_id;primaryKey" json:"dish_id"`
	Count       int16     `gorm:"column:count;not null" json:"count"`
	DishOrder   DishOrder `json:"dish_order"`
	Dish        Dish      `json:"dish"`
}

// TableName DishOrderList's table name
func (*DishOrderList) TableName() string {
	return TableNameDishOrderList
}
