// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDishStatus = "dish_statuses"

// DishStatus mapped from table <dish_statuses>
type DishStatus struct {
	DishStatusID int64  `gorm:"column:dish_status_id;primaryKey" json:"dish_status_id"`
	Name         string `gorm:"column:name;not null" json:"name"`
	Dishes       []Dish `json:"dishes"`
}

// TableName DishStatus's table name
func (*DishStatus) TableName() string {
	return TableNameDishStatus
}
