// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDish = "dishes"

// Dish mapped from table <dishes>
type Dish struct {
	DishID        int64           `gorm:"column:dish_id;primaryKey" json:"dish_id"`
	DishStatusID  int64           `gorm:"column:dish_status_id;not null;default:1" json:"dish_status_id"`
	Name          string          `gorm:"column:name;not null" json:"name"`
	Calories      int16           `gorm:"column:calories;not null" json:"calories"`
	Cost          float32         `gorm:"column:cost;not null" json:"cost"`
	Description   string          `gorm:"column:description" json:"description"`
	DishStatus    DishStatus      `json:"dish_status"`
	DishImages    []DishImage     `json:"dish_images"`
	DishOrderList []DishOrderList `json:"dish_order_list"`
}

// TableName Dish's table name
func (*Dish) TableName() string {
	return TableNameDish
}
