// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMonitorProducer = "monitor_producers"

// MonitorProducer mapped from table <monitor_producers>
type MonitorProducer struct {
	MonitorProducerID int64     `gorm:"column:monitor_producer_id;primaryKey" json:"monitor_producer_id"`
	Name              string    `gorm:"column:name;not null" json:"name"`
	Monitors          []Monitor `json:"monitors"`
}

// TableName MonitorProducer's table name
func (*MonitorProducer) TableName() string {
	return TableNameMonitorProducer
}
