// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePc = "pc"

// Pc mapped from table <pc>
type Pc struct {
	PcID        int64     `gorm:"column:pc_id;primaryKey" json:"pc_id"`
	PcRoomID    int64     `gorm:"column:pc_room_id;not null" json:"pc_room_id"`
	PcTypeID    int64     `gorm:"column:pc_type_id;not null" json:"pc_type_id"`
	PcStatusID  int64     `gorm:"column:pc_status_id;not null;default:1" json:"pc_status_id"`
	Row         int       `gorm:"column:row;not null" json:"row"`
	Place       int       `gorm:"column:place;not null" json:"place"`
	Description string    `gorm:"column:description" json:"description"`
	PcRoom      PcRoom    `json:"pc_room"`
	PcType      PcType    `json:"pc_type"`
	PcStatus    PcStatus  `json:"pc_status"`
	PcOrders    []PcOrder `json:"pc_orders"`
}

// TableName Pc's table name
func (*Pc) TableName() string {
	return TableNamePc
}
