// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePcOrderStatus = "pc_order_statuses"

// PcOrderStatus mapped from table <pc_order_statuses>
type PcOrderStatus struct {
	PcOrderStatusID int64     `gorm:"column:pc_order_status_id;primaryKey" json:"pc_order_status_id"`
	Name            string    `gorm:"column:name" json:"name"`
	PcOrders        []PcOrder `json:"pc_orders"`
}

// TableName PcOrderStatus's table name
func (*PcOrderStatus) TableName() string {
	return TableNamePcOrderStatus
}
