// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePcStatus = "pc_statuses"

// PcStatus mapped from table <pc_statuses>
type PcStatus struct {
	PcStatusID int64  `gorm:"column:pc_status_id;primaryKey" json:"pc_status_id"`
	Name       string `gorm:"column:name;not null" json:"name"`
	Pcs        []Pc   `json:"pcs"`
}

// TableName PcStatus's table name
func (*PcStatus) TableName() string {
	return TableNamePcStatus
}
