// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePcTypeImage = "pc_type_images"

// PcTypeImage mapped from table <pc_type_images>
type PcTypeImage struct {
	PcTypeImageID int64  `gorm:"column:pc_type_image_id;primaryKey" json:"pc_type_image_id"`
	PcTypeID      int64  `gorm:"column:pc_type_id;not null" json:"pc_type_id"`
	IsMain        bool   `gorm:"column:is_main;not null;default:0" json:"is_main"`
	Path          string `gorm:"column:path;not null" json:"path"`
	PcType        PcType `json:"pc_type"`
}

// TableName PcTypeImage's table name
func (*PcTypeImage) TableName() string {
	return TableNamePcTypeImage
}
