// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProcessorProducer = "processor_producers"

// ProcessorProducer mapped from table <processor_producers>
type ProcessorProducer struct {
	ProcessorProducerID int64       `gorm:"column:processor_producer_id;primaryKey" json:"processor_producer_id"`
	Name                string      `gorm:"column:name;not null" json:"name"`
	Processors          []Processor `json:"processors"`
}

// TableName ProcessorProducer's table name
func (*ProcessorProducer) TableName() string {
	return TableNameProcessorProducer
}
