// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProcessor = "processors"

// Processor mapped from table <processors>
type Processor struct {
	ProcessorID         int64             `gorm:"column:processor_id;primaryKey" json:"processor_id"`
	ProcessorProducerID int64             `gorm:"column:processor_producer_id;not null" json:"processor_producer_id"`
	Model               string            `gorm:"column:model;not null" json:"model"`
	ProcessorProducer   ProcessorProducer `json:"processor_producer"`
	PcTypes             []PcType          `json:"pc_types"`
}

// TableName Processor's table name
func (*Processor) TableName() string {
	return TableNameProcessor
}
