// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRAM = "ram"

// RAM mapped from table <ram>
type RAM struct {
	RAMID     int64    `gorm:"column:ram_id;primaryKey" json:"ram_id"`
	RAMTypeID int64    `gorm:"column:ram_type_id;not null" json:"ram_type_id"`
	Capacity  int      `gorm:"column:capacity;not null" json:"capacity"`
	RAMType   RAMType  `json:"ram_type"`
	PcTypes   []PcType `json:"pc_types"`
}

// TableName RAM's table name
func (*RAM) TableName() string {
	return TableNameRAM
}
