// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRAMType = "ram_types"

// RAMType mapped from table <ram_types>
type RAMType struct {
	RAMTypeID int64  `gorm:"column:ram_type_id;primaryKey" json:"ram_type_id"`
	Name      string `gorm:"column:name;not null" json:"name"`
	Ram       []RAM  `json:"ram"`
}

// TableName RAMType's table name
func (*RAMType) TableName() string {
	return TableNameRAMType
}
