// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameVideoCard = "video_cards"

// VideoCard mapped from table <video_cards>
type VideoCard struct {
	VideoCardID         int64             `gorm:"column:video_card_id;primaryKey" json:"video_card_id"`
	VideoCardProducerID int64             `gorm:"column:video_card_producer_id;not null" json:"video_card_producer_id"`
	Model               string            `gorm:"column:model;not null" json:"model"`
	VideoCardProducer   VideoCardProducer `json:"video_card_producer"`
	PcTypes             []PcType          `json:"pc_types"`
}

// TableName VideoCard's table name
func (*VideoCard) TableName() string {
	return TableNameVideoCard
}
