// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameVideoCardProducer = "video_card_producers"

// VideoCardProducer mapped from table <video_card_producers>
type VideoCardProducer struct {
	VideoCardProducerID int64       `gorm:"column:video_card_producer_id;primaryKey" json:"video_card_producer_id"`
	Name                string      `gorm:"column:name;not null" json:"name"`
	VideoCards          []VideoCard `json:"video_cards"`
}

// TableName VideoCardProducer's table name
func (*VideoCardProducer) TableName() string {
	return TableNameVideoCardProducer
}
